name: GitHub Actions CI for frontend and backend

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        # ✅ Inject application.properties for CI use only
      - name: Inject application.properties for CI build
        run: |
          mkdir -p backend/src/main/resources
          echo "${{ secrets.SPRING_APP_PROPERTIES }}" > backend/src/main/resources/application.properties

      # ✅ Backend Build (now works because properties are injected)
      - name: Build Backend
        working-directory: backend
        run: mvn clean install

      # Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install --no-cache

      - name: Build Frontend
        working-directory: frontend
        run: npm run build
